<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Android_Sanity_Test_Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>63806141-1bce-497d-b779-35b1af2c7587</testSuiteGuid>
   <testCaseLink>
      <guid>033433ef-323d-4564-b5a0-e94577ef3ac7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Account Selection/Verify Change Account From HomePage,Inventory,Carts)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ef3dae9-01db-45b1-9a12-f4589f28da13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>791e0b7b-e8d8-4995-b4d1-18be19b89d14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24d91f2e-ccea-4212-ba70-6aa116384f26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42b007bd-d4c8-4bbd-9f9a-994abf7eaabe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d880530-a3a3-416c-9ceb-145c75bf4d2b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b6106bd-e213-4b43-ae88-98c6b9ae22df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Carts/Submit Order After Edit Order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f75796e-4758-4b3d-b0ae-1bc18fa115d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c06d8c59-113b-4e1c-8691-571fe124ce30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c75dc44-3b46-4caa-8a96-774c4ce903f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e7c1081-b7e6-4b0a-9686-4d1bc44b2a7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f190d27f-dd57-462e-91dd-ca64d1ca9acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a72a484-ecc8-4ef6-b122-4cf600c0bbc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23073b01-bc74-494a-8abf-cb24093f6324</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7d5e79b-2e8f-49b4-a818-9dc31856eb99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45395b6a-8d96-47bc-ad8a-ffcf0309f0d5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a458d3b-6443-4e6d-afe4-441a9cf7e4b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Carts/Place and Upload All Orders</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f75796e-4758-4b3d-b0ae-1bc18fa115d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c06d8c59-113b-4e1c-8691-571fe124ce30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c75dc44-3b46-4caa-8a96-774c4ce903f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e7c1081-b7e6-4b0a-9686-4d1bc44b2a7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f190d27f-dd57-462e-91dd-ca64d1ca9acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7d5e79b-2e8f-49b4-a818-9dc31856eb99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5c81d4e-0b1b-4f3d-bb6e-a65b88af9a7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9367afe-84d9-4712-8322-5a4e1736a000</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ca3dabb9-0b43-41d7-a77c-32dbc59cf829</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Carts/Create Delete Order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f75796e-4758-4b3d-b0ae-1bc18fa115d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c06d8c59-113b-4e1c-8691-571fe124ce30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c75dc44-3b46-4caa-8a96-774c4ce903f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e7c1081-b7e6-4b0a-9686-4d1bc44b2a7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f190d27f-dd57-462e-91dd-ca64d1ca9acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7d5e79b-2e8f-49b4-a818-9dc31856eb99</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>09e8538d-29c6-45ae-813a-716f611a8e7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Carts/Place and Upload Order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f75796e-4758-4b3d-b0ae-1bc18fa115d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c06d8c59-113b-4e1c-8691-571fe124ce30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c75dc44-3b46-4caa-8a96-774c4ce903f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e7c1081-b7e6-4b0a-9686-4d1bc44b2a7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f190d27f-dd57-462e-91dd-ca64d1ca9acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7d5e79b-2e8f-49b4-a818-9dc31856eb99</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d8552b26-fb6d-47b2-97a6-2ddfb70c7d04</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Carts/Create Order by Search from Dashboard and Carts screen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f75796e-4758-4b3d-b0ae-1bc18fa115d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c06d8c59-113b-4e1c-8691-571fe124ce30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c75dc44-3b46-4caa-8a96-774c4ce903f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e7c1081-b7e6-4b0a-9686-4d1bc44b2a7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f190d27f-dd57-462e-91dd-ca64d1ca9acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7d5e79b-2e8f-49b4-a818-9dc31856eb99</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c4154f31-7a3b-4822-b18f-18d627ea64f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Carts/Adding Alternate Product</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f75796e-4758-4b3d-b0ae-1bc18fa115d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c06d8c59-113b-4e1c-8691-571fe124ce30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c75dc44-3b46-4caa-8a96-774c4ce903f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e7c1081-b7e6-4b0a-9686-4d1bc44b2a7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f190d27f-dd57-462e-91dd-ca64d1ca9acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7d5e79b-2e8f-49b4-a818-9dc31856eb99</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d8128738-d0da-435e-bfc9-b167e2d4766e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Inventory/Verify Inventory Location(Edit,Update)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebec2b9a-fab6-4351-9335-53b4fbe2eca3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c67c3197-d4f0-4a95-ab6c-8fcede197710</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a6f96bf-b7c7-4d6a-8ef6-b6c0b29976a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df9b9b6a-818a-48c7-bed4-77959214a2dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>441afb09-1301-40f1-98ff-1df1c3547219</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e52fdf29-be03-4ded-882b-9994e8ba01b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>948f2c9e-8ba1-4d5a-99a2-d545487c2e0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>802a7d45-31c6-43ca-8964-0eea65201b09</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0c1e00c2-e320-4644-864c-85f1fbdbad69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Inventory/Adding Product In Inventory By Search Verification</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a742363-83e4-4da2-b809-f8c20e510a9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc69bf89-cb8e-4332-8078-c886e3cf3505</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1885aebc-c425-4eb4-b7b6-12a2195b6a87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>757586b8-2fdf-4fd4-840b-629afe57630a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c5fd9ba-fe31-4538-aba3-2cca6dac865c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0905209-cb76-4e31-bd89-d182b6612a07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c538236-aa01-4bef-b2c6-445be0b63d10</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee409caa-f4cc-486a-9c04-c95a3da1bc4e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Inventory/Delete,Copy and Move Operations of product in Inventory</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebec2b9a-fab6-4351-9335-53b4fbe2eca3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c67c3197-d4f0-4a95-ab6c-8fcede197710</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a6f96bf-b7c7-4d6a-8ef6-b6c0b29976a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df9b9b6a-818a-48c7-bed4-77959214a2dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>948f2c9e-8ba1-4d5a-99a2-d545487c2e0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>441afb09-1301-40f1-98ff-1df1c3547219</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e52fdf29-be03-4ded-882b-9994e8ba01b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d425df9-2ace-48cf-aaf8-6234411e3604</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b165c53f-5466-4bb3-971a-ee4cf883b8d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Inventory/Upload and Share Location Details</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79cb9e88-168a-416b-89d0-6c8316516b16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22eb005d-2589-417d-abed-8c8222d014c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2eef52b0-31ab-480d-86c4-1ff9f7080800</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0861fda-34b1-4bb4-83bd-612ad9f2c9b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b562150e-eda8-4f56-b797-8922b1271972</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afe46407-495b-4fda-85ec-c9a960cf2bb7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>566e29d7-66dc-43e3-bed3-65da4a559b0c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Inventory/View Location Product Details</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79cb9e88-168a-416b-89d0-6c8316516b16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22eb005d-2589-417d-abed-8c8222d014c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2eef52b0-31ab-480d-86c4-1ff9f7080800</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0861fda-34b1-4bb4-83bd-612ad9f2c9b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b562150e-eda8-4f56-b797-8922b1271972</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afe46407-495b-4fda-85ec-c9a960cf2bb7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d6ebbcb-b6fe-47a6-98b4-8098d4062527</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Inventory/Inventory(Verify add,copy,move between location)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f63f558-da1c-40c2-b2ee-b00f3870c4f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbe1b4b7-f5cd-4c07-9b90-88ed55432cd3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ffcd80e-1406-46a4-ac3d-45e9111accb7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86b80f7c-e70d-480a-84f7-e91c817bf3c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eefda57f-7265-42ce-ade7-4bf3f74c5c77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>493bcc93-b576-4d5b-ab01-5507167a03ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>207a3fc6-e33a-4c3f-b24f-149d1de3e318</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed347973-326c-45b4-886f-b390032ff535</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>545beec8-a6b7-4bb2-9fa1-0abea8d2d90b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7243075c-da00-40e8-a373-81c1b5f9dac1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>adcff7f3-8d33-456f-96df-17d2b6767c95</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Inventory/Delete Location And Inventory after Adding Product</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79cb9e88-168a-416b-89d0-6c8316516b16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22eb005d-2589-417d-abed-8c8222d014c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2eef52b0-31ab-480d-86c4-1ff9f7080800</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0861fda-34b1-4bb4-83bd-612ad9f2c9b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b562150e-eda8-4f56-b797-8922b1271972</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afe46407-495b-4fda-85ec-c9a960cf2bb7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1c2525da-c830-4add-a986-cbae81acf008</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Login/Login Page Verifictaion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a25f688-79b0-4fba-8c08-df7924ab02a5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
