<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>androidSmoke</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>24965703-3168-4265-be11-587ace460d6b</testSuiteGuid>
   <testCaseLink>
      <guid>1d943020-8796-45a6-af24-38ece2294ec7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Inventory/TC_OE_003_verifyThatTheUserIsAbleToCreateInventoryLocationAddProductsCopyMoveProductsToLocation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22913fab-d9d0-47ac-b010-94aae5be4ffd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>390cfc0c-b3f7-4018-8211-b715f8e5da7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a5296bc-d918-463b-8159-44c70b82d84b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e9f9359-c86b-482a-ae69-c9abc4612d6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5029991c-0ffc-43e2-a885-2109ff70c44c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adce09eb-9999-46f8-9821-6c37321abe9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b92843b-ef09-49ad-a263-9c77af3fd458</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76315805-a949-4510-b69e-dee8de04d656</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0af75a3b-6697-444f-9c33-d01e96d4ace4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Inventory/TC_OE_008_verifyThatTheUserIsAbleToDeleteInventoryAndInventoryLocation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87fd13a6-6773-496b-b2c4-aa912478d8c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83872c8f-a6cf-44b6-aa23-27a5333f6ed2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b77561c2-ba45-4ce2-8fd4-138e750ffd47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>747d48b5-a86d-42c7-8782-ff5cb1fa5112</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e579b4f-e72c-40cd-bd7d-da37c77f989a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e59c5424-157f-4bb7-baef-b4b1b35ff234</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Inventory/TC_OE_009_verifyThatTheUserIsAbleToDoDeleteCopyAndMoveOperationsOfTheProductInTheInventory</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>638cc6ae-01de-4d85-9c92-48a4ba83c2b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c0721f9-679d-45d3-b8de-7759261237bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a35069b4-320f-4374-b976-3c0772e61790</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79a5569c-2bb7-4b78-a8d8-d23c152184ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05934aa3-9475-4cd5-a735-092dbd38eb96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d903a68-ab3e-4a27-9dc2-0d0f012b695d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc642b5a-4b35-42cb-97dc-e1d73546db9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>397773dc-19bb-4501-a6ac-e14852f5329e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb5d2cd9-0bd7-407c-9495-eb0ec8cdc449</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8230f5b9-a9e7-447b-9b2c-cbd1e0536f56</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Inventory/TC_OE_004_verifyThatTheUserIsAbleToEditAndUpdateInventoryAndInventoryLocationName</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d6afc5c-89de-4d51-a9b5-0988a4ed883e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ab609b0-d621-4714-9d93-dcddaad8f232</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1bebf98b-d58c-4662-b413-1a6a4ad2eacb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5dcd0a74-0079-4927-8dd2-d678dddd5062</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f840750e-5741-44c8-8905-6fac15954d35</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9c0f05d9-3d35-464b-a603-fcf1aec635bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Inventory/TC_OE_007_verifyThatTheUserIsAbleToUploadAndShareProductDetailsInTheInventory</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f8e6193-7f5b-494a-8127-eb5ddecb1fcc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2333786c-6076-48db-bafd-7d6ee9e4eb0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>567a98bf-3e5c-4082-b8ba-af4012089295</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdcaf44a-f2a3-404b-a5cf-f99da8cfffe7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66430929-e261-4f88-a492-3daf98e58d2e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3949a36a-23f8-43ec-a08e-493abf96bf7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Inventory/TC_OE_005_verifyThatTheUserIsAbleToAddProductInTheInventoryBySearch</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80c9df56-873f-4de1-9351-d276c4bc8f2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db013d39-58f5-4681-9a2e-37a931bfc132</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c57c3fdf-34be-42fb-a182-9668f7b2f9a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dd9d174-f1aa-4af1-9ea0-dd1a61a00120</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d04a0faa-4357-4ab7-b657-8c6031ab6ee3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>64707025-01d2-4f96-8eee-52ca29ad1ffc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Login/TC_OE_001_verifyThatTheUserShouldBeAbleToLoginInOrderExpressAppUsingValidLoginCredentials</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ffa0ae8a-5bc2-4ff7-9a1b-f4f2360f9bf8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Carts/TC_OE_010_verifyThatTheUserIsAbleToCreateAnOrderBySearchFromDashboardAndCartsScreen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>441c6c23-663f-4907-8c69-cde42d67b18b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07a3b5a0-d693-4e22-b49c-3f4f718d526d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab017002-6451-4b5a-8020-fe92acf41893</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b50c6953-30fc-40f1-a32e-7b48736a331c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4211460c-522b-4a1c-bbe8-e963723dd6f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2470760d-5416-4b4c-a2d6-d2975a7965ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b95d42c-174c-49a9-861e-229abe2de0fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>93b0dcfa-2fe7-42a1-aef8-5baf5bea9421</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Carts/TC_OE_012_verifyThatTheUserIsAbleToUploadAndPlaceOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a09fa3e2-6772-4562-8155-33b6833b066c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0eb3d61-7fc8-40a7-ba2a-39720666f655</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c32ccbd4-ab7d-43d8-93a8-d0bcef1e5c07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f232d83a-c3d1-4e46-ab2a-10cd1ed503c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57f40c89-7206-4c6b-be30-573712411b2b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76e3e371-0859-49fb-bc94-997b294059d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Carts/TC_OE_013-verifyThatTheUsersAbleToPlaceAllOrdersnAdUploadAllOrders</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>551a562c-08d2-4feb-b6ba-e7206405f725</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77f636d7-3588-4367-a71e-b257eedfc6f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb636019-1db9-422f-aaaa-7de4f8648c9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c06ab44-eb72-4dd2-8dfc-dc1154cc6499</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05ccc3d2-d01d-42f3-a5ce-8a39de0a0e07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b170bd90-b950-477c-a425-fce9e1afae1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2b47834-b004-4e59-9952-959d7b4eab2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2ead715-5657-4723-a975-f6a5f9ff781b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>405fe802-1567-41d5-b0fb-86364d4ac329</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Carts/TC_OE_014_verifyThatTheUserIsAbleToSubmitTheOrderAfterEditingTheOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ad4fd3f-a262-4660-9a3e-69305febbac5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bfa337c-6290-495f-80e1-727652fc79ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7bcb657-650e-4ba5-add0-6ff24922e4e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c1e68f9-31ed-4ee1-9dcb-235340b24006</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0c979cf-e5c4-4ef2-8540-4f6bc328c6d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>95daeba9-0fb6-48a6-a39f-31399f82bf8b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Carts/TC_OE_015_verifyThatTheUserIsAbleToDeleteTheOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>164e2487-0844-4318-809d-94d39179af1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>824ead39-7675-4ba1-8acc-e5d59355c4b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01b2b41a-8053-49dc-be9b-245a59078573</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f3c550a-e268-4987-aaa5-9cbf812fadfb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6719084f-3ef6-4d58-be88-09dd0d000ab3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Receiving/TC_OE_023_verifyThatTheUserIsAbleToEditTheCountValueOfTheProductsInTheTote</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>576f9cac-73a2-48ff-8999-16c1705f11ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc5e2c83-4c63-4762-ad72-f60d0a3e6cf5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ee7ef24-9a11-4f2a-9f38-89b25714b54e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c001ba54-b7bd-4d41-ac49-74ad964a46a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>123b8a39-34e6-4f24-87aa-c37f78434a94</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bbb748f-2a0e-44ff-b6cf-da4199d47fff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Receiving/TC_OE_021_verifyThatTheUserIsAbleToSelectReceiveToteButtonAndUploadSelectedTotes</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24899e58-0c8b-4691-b6b0-15ac18db9dff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61901ca4-1a8f-49bc-ae0f-5391ddaaa7d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a151015b-60dd-4d00-8a9f-e68a81e1e42c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a205aa41-1b4d-4ee3-8f1d-1e08e65f5c97</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b6d0d047-e0d6-4806-9b04-21175e34f2a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Receiving/TC_OE_020_verifyThatTheUserIsAbleToSwapBetweenShipmentsAndInvoices</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2990d609-4750-448f-a63e-c4d6206aa03f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0da349ac-e3ba-4e19-8614-6915d4c721ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6606458a-836a-4850-bfcf-cd89d329134f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Receiving/TC_OE_038_verifyThatTheUserIsAbleToGetTheScanResultByDoingTheToteLevelScanning</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d76a13f-c208-4ee9-a3f5-f0f5559cf32c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8ef698b0-daf1-42b5-9169-ff4930accc2a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Receiving/TC_OE_018_verifyThatTheUserIsAbleToViewReceivingPageAndReceivingData</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bbb5468-ec9b-411b-8e58-09ecfb99c3af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d8962af-e0e5-44a1-b1ac-5fbf08b9fb6d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b657365e-c355-4f1f-b441-7e33abc2660a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Receiving/TC_OE_022_verifyThatTheUserIsAbleToDoAllowOveragesAndEditCountOfProduct</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a419710-c9a4-40d2-96e8-283732e68093</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9b9cd32-7a00-42f1-85d7-f3bf336582c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>257cb7d3-1c6f-43a9-b75a-51474dbcef08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1cba0d53-b1e9-4379-aa8b-72f875115e6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a4cc906-cc57-406d-a053-fa534532039d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f8aeb577-0d44-459f-9ef8-6d7d6108cdc7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Receiving/TC_OE_026_verifyThatTheUserIsAbleToSubmitTheIssue</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17ee4219-eaa8-4cb4-8973-2ff7a5796e01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba2ef07f-d7a4-4f4d-aa80-c255797dd7fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfb33c4b-67ec-4085-b6bf-585fcbaac8c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ed4d5bc-710f-4475-ac48-e06081ec469c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d756be94-e3f3-40ad-a92b-38d528d31c78</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9362264-b4f1-458a-aea7-192974634209</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b87d61fd-d9af-4e05-afba-31e39d569111</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>75e3eda0-887d-4062-98e8-e5c464ed794f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Receiving/TC_OE_025_verifyThatTheUserIsAbleToSearchTheProductsByScanningTheBarcodeWhichAreAlreadyReceived</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bafc9da-df0e-4d14-9968-d782ae43f4ea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24a5376a-e7ed-48f4-84fe-448860cf3228</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Receiving/TC_OE_024_verifyThatTheUserIsAbleToSearchTheProductsAndTotesManuallyWhichAreAlreadyReceived</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d4a9d34-687a-4e71-b931-975781addb75</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>89a2fa82-273f-439b-a645-a9b3de13f95c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Receiving/TC_OE_019_verifyThatTheUserIsAbleToViewTheReceivingDataOfThePreviousDay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24899e58-0c8b-4691-b6b0-15ac18db9dff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61901ca4-1a8f-49bc-ae0f-5391ddaaa7d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>691f6105-c419-4140-a8eb-c65017cda603</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Audit/TC_OE_027_VerifyThatTheUserIsAbleToViewTheAuditsPageAndChangeDifferentCIMaccountUsingAccountSelctionIcon</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41a87957-03dd-4979-9cf4-a7370cf20eba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54fd8fe1-f53b-4995-bda5-c7092bdc0455</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc819983-63cd-4be6-b1ae-94b7b8a44abc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f404300f-08a7-45db-9b6a-4debf43be32d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/android/Account Selection/TC_OE_002_verifyThatTheUserIsAbleToPerformAnAccountSelectionUsingTheAccountOptionAvailableFromDashboadCartAndInventoryPages</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b3bf1d4-c8b8-4dfd-82cd-fb90d783914d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5998bf7a-84ec-4787-92a5-9915ab6fecaf</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
