<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>androidRegressionSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d625e5e9-54c2-40d9-bec5-424457bbe620</testSuiteGuid>
   <testCaseLink>
      <guid>4897f23b-0a24-4df3-b429-37ea3d66ce5d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Receiving/TC_OE_020_verifyThatTheUserIsAbleToSwapBetweenShipmentsAndInvoices</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2990d609-4750-448f-a63e-c4d6206aa03f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0da349ac-e3ba-4e19-8614-6915d4c721ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70e5f5c5-ded6-49f5-b8c5-bf3331a05d60</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Receiving/TC_OE_018_verifyThatTheUserIsAbleToViewReceivingPageAndReceivingData</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bbb5468-ec9b-411b-8e58-09ecfb99c3af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d8962af-e0e5-44a1-b1ac-5fbf08b9fb6d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d4fe449-72fa-4f1a-b9e3-e0eb502dcff6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Receiving/TC_R_001_verifyThatTheUserIsAbleToGetTheDetailsOfReceivedProductByScanningitsBarcodeInReceivingPage</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1336d1bf-f61f-4298-8b58-8e5d4bc60c6e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Receiving/TC_OE_019_verifyThatTheUserIsAbleToViewTheReceivingDataOfThePreviousDay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24899e58-0c8b-4691-b6b0-15ac18db9dff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61901ca4-1a8f-49bc-ae0f-5391ddaaa7d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>895cf50f-e805-4fc6-ace8-8e7e85ad1f65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Receiving/TC_OE_022_verifyThatTheUserIsAbleToDoAllowOveragesAndEditCountOfProduct</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a419710-c9a4-40d2-96e8-283732e68093</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9b9cd32-7a00-42f1-85d7-f3bf336582c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>257cb7d3-1c6f-43a9-b75a-51474dbcef08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1cba0d53-b1e9-4379-aa8b-72f875115e6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a4cc906-cc57-406d-a053-fa534532039d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ee3be27-430a-4854-b53d-de9cf80c93ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Receiving/TC_OE_021_verifyThatTheUserIsAbleToSelectReceiveToteButtonAndUploadSelectedTotes</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24899e58-0c8b-4691-b6b0-15ac18db9dff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61901ca4-1a8f-49bc-ae0f-5391ddaaa7d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a151015b-60dd-4d00-8a9f-e68a81e1e42c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a205aa41-1b4d-4ee3-8f1d-1e08e65f5c97</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9988c98e-7181-4eea-bfb0-68b386d16e20</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Inventory/Scan Test Cases/TC_R_023_verifyThatTheUserIsAbleToUploadTheLocationFromLocationDetailsPage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5b49d63-cfed-419a-be87-31b8531271ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96d4c384-0e25-4d04-9c06-b9d9921bf0ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29b89f10-c107-4e20-9b46-73b812637a07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2ce5182-c72c-4e2f-9576-7060108c6233</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>769553a0-9e20-41e9-a715-d5f5dcbb609f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>836b043e-15f4-47e0-a37d-e3f2d3d676de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Inventory/Scan Test Cases/TC_R_015_verifyThatTheUserIsAbleToDeleteInventoryAndLocation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>726a234c-cc29-46e6-a51c-5d6e909ea63b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a92c899-747a-46dd-9b54-5b50412b912e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e3f23b6-1078-461f-abc4-5b0325f87637</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35d19441-05a0-4487-a92c-df13bc8a7b8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d852407-f3e8-4a2b-82ad-d86ac825ee18</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1cc6dc6-0718-4887-9da6-dd5b88001d39</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Inventory/Scan Test Cases/TC_R_010_verifyThatInTheLocationDetailsPageTheAddedProductsAreListedInReverseChronologicalOrder </testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9e7d10d-8935-4f2c-a14b-1973198ac60f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57694bab-13f2-4a21-86a6-97dda5b6be07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d34ed936-a8d6-4538-8f00-23d49f403c44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f86c51f-c891-4ef6-bdba-58728db93683</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cb53523-20f6-44f3-9424-5df7538ceb17</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d75ed26-1058-4f1b-821d-cddb8bb2e859</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca1bc8f7-899d-4f00-b41f-d7f74c9c8fbf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b4b20f9-2dcd-4189-989d-87dd5e50aa8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Inventory/Scan Test Cases/TC_R_046_verifyThatTheUserIsAbleToDoCopyAndMoveActionsOnSameProductsInTheInventoryLocations</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7c6a101-9902-4d14-8b8c-eb26e9dbf964</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d08197b-ce7f-4bb0-b04f-daa25052c73c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e1c2d3b-14d1-4118-8353-6af6fe0d5f71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85b6ba4a-49b1-43ff-ad88-99aca58f4f89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcd39d5e-8323-448a-9830-ec615544bbcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de2d1173-6fef-4ac1-a6d9-97f61bcecb58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>574701a1-2ba8-4be8-acbc-edcec06f1043</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82f036cd-beb9-4317-91e2-005beced9fc8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53ed444f-c3e8-44a5-83b1-72dae0f8e219</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db58be5a-09c1-4409-8d72-0441ae832555</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0caba7e3-50e5-49cd-97d9-0f6574864e24</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>02547037-6608-4efa-9007-06d2dc2e0b9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Inventory/Scan Test Cases/TC_R_020_verifyThatTheUserIsAbleToShareTheProductDetailsFromTheLocationDetailsPage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26dfb16d-d2df-405f-8712-d4f3ec06be73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d6563bd-3acc-40b9-9ee0-72e12b0ffa5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f168128-c823-4dcb-8027-1cc4044e3f04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08b2fb12-1ffe-4caa-a740-2a2a304e5b85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cf47ad5-31e8-49d7-b6a9-ba5c6d1095ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efe23545-a070-4aa4-89b0-877888da0549</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fc249002-b6a9-4a3c-99a3-f0e149612388</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Inventory/Scan Test Cases/TC_R_021_verifyThatTheUserIsAbleToDeleteTheProductFromLocationDetailsPage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8aa528db-05f5-4f7b-8fff-ef43808b2c16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e9d6bd9-8bd6-49b2-b9df-84271064d3d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a18f0013-9808-4409-be7a-1d2e23a4f1ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8007995b-d754-4ab1-a965-83eb21ece9a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee05636e-eef7-448d-a800-510bbb666fc0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f50a6c1f-efd5-4223-a84b-4a684a47aa45</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Inventory/Scan Test Cases/TC_R_003_verifyThatDetailsSuchAsLocationCountInventoryValueUpdatesAfterLocationDeletion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b09fa49e-6084-47f3-8048-4a7ae170b86a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0e0cbf8-9e1b-4c1a-9f94-d2857adf446d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49416f63-c90c-485e-89d1-6fdd57b75897</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>275ca5c0-e6ec-494f-909e-aa6bd62a3984</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bb3f865-dad8-4101-8f1d-7c78cb0ce185</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0158195-9939-454c-8599-81156e532dc7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Inventory/Scan Test Cases/TC_R_034_verifyThatTheUserIsAbleToDoDeleteCopyAndMoveActionsOnDifferentProductsInTheInventoryLocations</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6273bd0f-b06f-4147-9338-9162c8eebd14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e059c2a-0798-464d-b2fb-ad3f0358a43e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05493609-51ec-498d-bcc5-a3806bd25cdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e17d21c0-f7e5-4c1e-83b7-a9b3205b9213</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12229713-a368-4623-a9e4-97434c05d8df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67a87807-2a32-44d3-a796-4e2a2b302d26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9da93892-bde7-44b2-ba97-ef96d5c6f071</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c177d248-46a9-4803-bc6d-faf3f0af219e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c581869-a16a-4abe-8f36-dd8cb96bc98f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>038b8211-2365-49a7-b682-c846dfc22f4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a52d3e1a-d34e-445c-813f-c7876493a397</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1090ec9-bb73-4edd-8bd5-d0cbc50c76bb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b1393f7-4a55-4a67-873e-faf79ccb0194</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Inventory/Scan Test Cases/TC_R_019_VerifyThatUserIsAbleToIncreaseTheProductQuantityByScanningTheSameBarcodeAgain</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b18e901-f7c6-4f90-a8e8-525e1087d3ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>440c2246-f291-4dd0-9745-a07e0a67ebe9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34920892-7e98-409e-9ea4-17cc6f63fe29</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>154434fd-3916-4fd9-b1df-159e852e4ccb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>319a8e49-6ca7-458c-a2c5-ac97f802a822</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b42d843-09c3-4279-91f3-abaff2cc7a0a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Inventory/Scan Test Cases/TC_R_007_verifyThatTheUserIsAbleToUploadTheLocationFromLocationDetailsPage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8232e0b3-cfea-4b9e-a4e5-181289aaca40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0efaa64-5dcb-4229-9e31-e047521771b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3adde9a9-bb08-4ef9-a105-37f7359679dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e58e617-6a8b-4547-afb5-3b5b8ac6fa60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c851f6ff-9a3a-41b6-8d69-6457333668cd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c424a1b0-373a-4b0a-9dc7-b544e603c7b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Inventory/Scan Test Cases/TC_R_017_verifyThatContinueBrowsingButtonInInventoryScanWorkingFineWhileDoingScanFromTheLocationLandingPage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31e502c9-17b9-4d5f-ba9a-1fdaf1484688</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>945e2480-1246-44fd-b51b-b63ccdb76c84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c59de9d-92a3-4d79-8a1b-f846bcf5bc33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ec202d2-9b8a-4460-a135-eed21dfd395f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4991f361-b03a-4ce6-a57a-455809a32b89</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>81fbf6cd-e47d-4759-8d8d-ec5d2b55d84a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Inventory/Scan Test Cases/TC_R_018_verifyThatWhenUserTapsOnRemoveButtonInTheInventoryScanResultPageOfAnAlreadyScannedProductItGetsRemoved</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5950ac15-d96c-47e3-8602-dce32832c5c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15311d93-b186-4539-88c9-013955ac3e44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c45cfafc-4406-43ce-9e5a-c3efa5d38e6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5a8ab81-6128-4d80-8888-0120a0510518</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ae1a2d9-6a78-4fe8-9686-ab747ec1ae77</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0650edb3-de80-4434-8959-039d740139fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Carts/CSOS/TC_R_072_verifyUTNvalidationIsHappeningFineAndUserIsDisplayedWithTheDuplicateUTNNumberPopupIfTheEnteredUTNIsDuplicate</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5dd05330-b677-4c12-a4bd-12fb8c732cb3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>945c5f43-45a7-46e6-a1e8-3e979bb35488</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea48d9cf-be64-4c02-b0e0-596bfc8a843b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9dc74450-8a2d-4c8b-b41a-e08a54528f01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8aba244f-be9b-43a2-af35-7afd93ae960e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fb793c4-b190-42d7-be42-f1d74a1ebb12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40cf78cb-91fa-42aa-8b30-151644675173</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f614129-7173-4f2f-9a13-052a231ccf20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17e8f8d8-b2d8-4e69-b1de-c4be2aaa2dd0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef96487f-5a9f-4805-a6cb-353eb1373d80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a4a6086-27a3-4fad-8877-0ed1783c0eba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>982f4740-381f-4947-aa93-de5b9a90da43</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Carts/CSOS/TC_R_071_verifyUserIsAbleToSignAndPlaceOrderInOrderHistory</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5dd05330-b677-4c12-a4bd-12fb8c732cb3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>945c5f43-45a7-46e6-a1e8-3e979bb35488</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea48d9cf-be64-4c02-b0e0-596bfc8a843b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>206fb97f-da39-46d2-a4f9-fe520127a61c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Carts/TC_R_058_verifyThatUserIsNotAbleToAddC2ProductFromProductDetailsScreenToAlreadyCreatedNonC2Order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1da55bec-1a71-48ee-8260-15512542f42d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7587685e-69cb-4d16-9805-0f6bcef96da5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0da45239-8e65-40c7-ab13-4c4ff22ada4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37c82b07-979c-4cc4-a473-02b2daac8dda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dee26c8f-317e-4ae7-8488-07df7241c4f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bab95f46-2052-41e2-a98f-824e05b9d7c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Carts/TC_R_005_verifyThatTheUserIsAbleToUploadTheOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d98657c-cee3-4d4c-9dd8-37983cdce84c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96001e33-53cb-4d94-a911-fe72c255304a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bab36757-295b-4bfa-bacf-92431e605e3b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d41c980-3510-4b93-904d-753c5c577cdb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c2a4d00b-5f27-4a53-b5c4-4ad6300c8df9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Carts/TC_R_045_verifyThatWhileUserScanNonC2ProductFromTheDashboardAndAddingItForTheFirstTimeNewOrderOrderIsGettingCreatedAndUserIsAbleToUploadTheOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a39cc83-d261-4c6e-898d-cac961bdf7e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eaf66315-2e6a-4683-9efe-b52aa77fc43c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d20bf1f-05dc-4496-a202-fca6f7cc5db8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b4dba07-bef1-4538-8911-6f4032a5db46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f56b3890-cca5-4a90-950f-d4fea8e9b354</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3864ea1a-8054-4bc6-b2ef-e3f945eed056</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>391f598a-8708-44c5-ae82-d7ad7a69a911</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6cb65b71-1b48-4756-bf11-4c0139ed318d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13bb4a29-0433-4389-9e6f-9ad922c11191</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdc127ef-1748-4f39-8a66-bc2bb67998ba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ec435d80-48f1-4ebc-a004-88a8da9703db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Carts/TC_R_043_verifyThatWhileUserScanAC2ProductFromDashboardAndAddingItTheForFirstTimeNewOrderIsGettingCreatedAndUserIsAbleToUploadTheOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cd85ec7-e505-4d4a-a5c5-85f9e5ffb2fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f884d9fa-c80c-487b-9dd9-fca401a54279</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f67a1a8-12e3-4179-a17c-e434437a133e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>169844b9-e66b-4494-adc4-a9368defcf15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e66d32a9-2e47-4150-aeb3-db165d76466a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7482030-4458-465b-aac1-a25788efa78d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9f3282a-477c-48c4-8621-365498e823cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61011208-1dd7-49a0-b72e-e3aade833a46</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ad5e5e64-a1fb-406c-88dd-db714815cf27</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Carts/TC_R_044_verifyThatWhenTheUserScanAC2ProductsFromDashboardAndAddingItMeansThoseProductsAreGettingAddedToTheAlreadyExistingC2Order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64b25276-eb30-421f-b195-33e1a06194a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>510c4a3a-26be-4bc6-8bdf-d8726ec41ae5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cfa002a-0b17-4803-ac84-87ad844c758b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3821a579-0ee2-42cb-820d-65f02dff2618</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3437275-7a9c-4cc4-83dc-f783de88a3ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27388fef-afd7-4bc8-a1ad-f9ab9734d6bd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a38c4a8-3a12-4819-ac1c-24ffee2fd2d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Carts/TC_R_059_verifyNewOrderCreatedWhileAddingAAlternateProductFromProductDetailsPageWhenThereIsNoExistingOrderFromHomeCartScreen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>705a16b9-bb6c-4a11-9701-369e10481ab8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea019682-dce6-46b5-96d3-cc2cd5c5cf8f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34149f75-2405-4cce-a0e5-4512ac2f5f79</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Carts/TC_R_060_verifyNewOrderIsCreatedWhileAddingAlternateC2ProductFromProductDetailsPageWhenThereIsExistingNonC2OrderFrom HomeCartScreen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72b263d5-0f5c-46a2-87ca-2dd6bbab52cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>373b9b3b-ac15-4482-ae00-a41b5b08a3b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29e28254-5017-481c-842e-2c4796f5dcc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e06d4b7-130e-4440-b7cc-4698895f54f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aede4838-31f3-42af-b5de-a42aa8e761f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7be6dd0e-6944-4ccf-9079-5ceeb65a2e64</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Carts/TC_R_051_verifyThatAfterChangingAccountUserIsAbleToCreateAnNewOrderByScanInCartPageOnCurrentlySelectedAccount</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3146a980-0b4d-4253-a16f-26058cdafe31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8812b5e-ca5b-40d9-8d8c-df6c7cfe1a51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71681d51-56f8-4d15-8003-b29ec310815f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9120c4c1-7e3b-4ebb-aedf-444a9c4b16ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>603c25f0-15a5-41ef-b1e3-43a366be2c10</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a18a3de4-f735-4f0b-9d6f-607a910d440c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e712914-bb16-4d2a-a424-a5bc088c473c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c177e1f-4ae7-4fb8-971b-ca6d41112f62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f98d65d4-acfd-4ca5-8adc-6f40d504fe8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33731098-4a7e-471c-8018-a5f8e6d4fb68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5eb79755-dbe5-43fd-bd20-2651387b6b33</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea8d6c2c-f105-4636-8721-6b0e9a97bdef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Carts/TC_R_061_verifyThatUserIsNotAbleToAddNonC2AlternateProductFromProductDetailsScreenToAlreadyCreatedC2Order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b447744a-f6bd-4f4b-979b-c90bcbb48429</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dde95e5-097c-4def-89dc-71d94f72d52f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e519061-2e35-4e9b-ae7f-eefb70013c96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6251c5d5-aac8-44d1-a200-0497f61d77e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9b37f2f-f122-41ff-8026-d6cc9987f3fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1dde6160-b372-43f7-b0af-f18099f5fea3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Carts/TC_R_053_verifyThatAfterChangingAccountUserIsAbleToCreateAnNewOrderByScanInDashboardScreenOnCurrentlySelectedAccount</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12cbbfed-8a06-42e2-8fcc-933b3e6acb8a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8ffa63e-6b3c-43d8-8dd2-985525acafa7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01165007-36be-4ee4-a8db-54ac95407662</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40ddd510-fb26-46c5-9ca1-70d7a35665d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d04ff7fc-1e8b-4d7b-8dc2-4dbc39f61b3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa5032b7-6f7a-44c4-b6c8-21cb7e54b975</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d8f03ef-db87-4d1c-8d04-e513dc5ac240</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d72c0e35-3d19-4352-ad52-f3a3c8521475</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Carts/TC_R_049_verifyNewOrderIsGettingCreatedWhileAddingC2ProductByScanFromCartWhenThereIsNoProductsInExistingAvailableOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e153445b-6287-4bb6-b691-fe1820aaf6f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75b75912-5e37-42fe-8a69-15ed35f5e41a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00f4f3f7-8b9b-4776-84d2-b61e927e4871</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>748fadf8-ff2a-4ec1-93b8-98d5aaefced2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b0e1383-e503-463e-b53c-6753e47e01aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0e4d859-99ae-40f4-81d4-d3347719be2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7eb6e13-0c8e-4d6c-8323-18c6587d8d5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edf2f8d1-4ae2-4608-b6b6-067260ee4180</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ab2ac5e-2f26-418a-8d7a-7db77fb859a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e754b577-2b05-42eb-ba1f-e69203488aa8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73842a4a-ee01-477f-810e-8888f7fd2db1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>58c142ff-1422-4bdf-90bb-c266941f4f36</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Carts/TC_OE_011_verifyThatTheUserIsAbleToCreateOrderByScanTheBarcode</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31d96026-556a-478b-99b4-ae21a3c11ab5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>300e7820-f2b3-4dd3-8f8e-1dd12ec26aa7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e236e395-5aef-42fc-83b7-2f4fddebeeba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a4de2df-0fa1-4189-a8c9-5ce3a9ac1809</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8039d2be-d372-4d5c-aede-c48a01c472c8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>66fa5340-6013-4856-9e83-5fc2adc78737</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Carts/TC_R_035_verifyThatTheUserIsAbleToPlaceAllOrdersAndUploadAllOrders</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16a887bd-6553-4d8f-87aa-27cb3624116c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14164266-a9e0-42d8-b10c-1cf8ae85dd19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2d6fd18-28ac-4187-8014-2f6c8e8e6503</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51d709d9-219e-4d47-9d73-65770123b7cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17926b3f-81fc-4a52-b6c9-9035c6cba613</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbda58a2-27ab-4dd3-a612-9c675327dde0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a081cd4-afbd-49e7-98e2-7e4bf8baa986</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92279605-d17f-458f-8e8d-402fa3f01411</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
