<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>iOS_Sanity_Test_Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9113850e-f74b-4cd3-b3c7-788bf22cd30e</testSuiteGuid>
   <testCaseLink>
      <guid>59b7dd9d-946d-420e-9ff1-539e8e0ece5a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/LogIn/Login_Page_Verfication</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42708fd8-c6d7-4e56-b380-964f0a0acba0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e5ce8d11-80e0-410c-b7aa-1b7980ef5b57</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Carts/Submit_Order_After_Edit_Order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfbe3cb5-7ec5-4a36-99a9-86e4f22e09f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e948eea-5532-4b5b-8fbe-044ca16dc1e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>197ff2fb-608a-4b1f-aaa9-160b3b06a43c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07b18a79-2e06-437e-8592-83b13a1c5b74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccb40310-7d70-4ab2-bacc-a027260f37fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbf04899-eb7b-4a60-839d-9ffce70f6f03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24403616-24d5-4c25-b5aa-a616c2cee56c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ee0ae57-fb51-4db9-babd-4baf2d346317</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72bdefbd-1eab-465c-bd68-c36351a89bbf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>509384f7-0f3c-45a0-8da5-e218dcdd3692</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Carts/Create_Delete_Order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42708fd8-c6d7-4e56-b380-964f0a0acba0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd9cb911-f473-4748-8054-37b973a361cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfbe3cb5-7ec5-4a36-99a9-86e4f22e09f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e948eea-5532-4b5b-8fbe-044ca16dc1e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>197ff2fb-608a-4b1f-aaa9-160b3b06a43c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47ed8663-cdef-4572-b8a4-8874f8854522</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcb3bd4d-c60e-4b5d-b148-aea87b4802e3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4db440f8-cc7d-43e1-bcf6-4b33017483cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Carts/Place and Upload All Orders</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfbe3cb5-7ec5-4a36-99a9-86e4f22e09f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e948eea-5532-4b5b-8fbe-044ca16dc1e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>197ff2fb-608a-4b1f-aaa9-160b3b06a43c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbf04899-eb7b-4a60-839d-9ffce70f6f03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a29037a-1f52-4047-9615-c4a471ff5d59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>def51907-c05d-4e65-aedc-9de0444a3097</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>be3f41ff-df23-4863-a504-48a518b87f90</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Carts/Place and Upload Order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfbe3cb5-7ec5-4a36-99a9-86e4f22e09f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e948eea-5532-4b5b-8fbe-044ca16dc1e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>197ff2fb-608a-4b1f-aaa9-160b3b06a43c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbf04899-eb7b-4a60-839d-9ffce70f6f03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a29037a-1f52-4047-9615-c4a471ff5d59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51fdacd4-50d8-49c1-aa9b-6ea645abf79e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c2f48d11-955a-4482-b973-69b8de3b9a99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Carts/Adding_Alternate_Product</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d701e37-ad90-4484-9a78-7aeba887ba50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfbe3cb5-7ec5-4a36-99a9-86e4f22e09f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e948eea-5532-4b5b-8fbe-044ca16dc1e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>197ff2fb-608a-4b1f-aaa9-160b3b06a43c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbf04899-eb7b-4a60-839d-9ffce70f6f03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a29037a-1f52-4047-9615-c4a471ff5d59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b012800-161e-4398-ae38-fdb5500d335d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c96366db-1055-4b6c-a6e4-6af406292df2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Account Selection/Verify Change Account From HomePage,Inventory,Carts)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42708fd8-c6d7-4e56-b380-964f0a0acba0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47ed8663-cdef-4572-b8a4-8874f8854522</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb0d0e60-c03b-4615-8443-734ef797afe3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a760b561-697c-40e1-9e7f-c70cbf8e89bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a47a4c56-67c2-4cda-bd67-5c333a349e65</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>592e5a7f-4dad-4295-83be-17127ce8506b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Carts/Create Order by Search from Dashboard and Carts screen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42708fd8-c6d7-4e56-b380-964f0a0acba0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfbe3cb5-7ec5-4a36-99a9-86e4f22e09f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e948eea-5532-4b5b-8fbe-044ca16dc1e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>197ff2fb-608a-4b1f-aaa9-160b3b06a43c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcb3bd4d-c60e-4b5d-b148-aea87b4802e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c63ea2d-deca-42bf-af4f-41dacc6ec618</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd9cb911-f473-4748-8054-37b973a361cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47ed8663-cdef-4572-b8a4-8874f8854522</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>13833048-0d5a-4b8e-b227-022a8e1ae1ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/Verify Inventory Location(Edit,Update)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9afa028-56d1-4071-9ac2-d92082e422c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8232e0b3-cfea-4b9e-a4e5-181289aaca40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0efaa64-5dcb-4229-9e31-e047521771b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e8eb048-9ede-49c0-8853-4f826e648887</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3adde9a9-bb08-4ef9-a105-37f7359679dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd9cb911-f473-4748-8054-37b973a361cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35bd1993-b85f-45ac-9b82-4b65398bef76</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>50573be2-4af7-448d-9aca-a310b3d4a866</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/View Location Product Details</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9afa028-56d1-4071-9ac2-d92082e422c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8232e0b3-cfea-4b9e-a4e5-181289aaca40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0efaa64-5dcb-4229-9e31-e047521771b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e8eb048-9ede-49c0-8853-4f826e648887</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3adde9a9-bb08-4ef9-a105-37f7359679dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd9cb911-f473-4748-8054-37b973a361cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a59d64b-5aed-4166-8a42-373fc8259a7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29a063cd-0050-43d8-b55a-4f5857bdb8c5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fcea69d7-4606-42ed-b96c-8363d590c2ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/Delete Location And Inventory after Adding Product</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7b3c050-18b7-46f6-9f1b-ea62e54be902</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ca5537e-aa3f-4334-ba3a-c3b7cd483828</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fab8d24-41d4-40b2-8b6f-a8bbb041916f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fb2dfe9-c2e4-4f40-877d-0f22ead3196b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef812128-c67c-4e9e-ba64-5653bd17f77b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa95574a-3863-4465-9265-74d0a268dd6e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20007741-c615-4dba-9eab-20250a48a7a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/Adding Product In Inventory By Search Verification</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ca5537e-aa3f-4334-ba3a-c3b7cd483828</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7b3c050-18b7-46f6-9f1b-ea62e54be902</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fab8d24-41d4-40b2-8b6f-a8bbb041916f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fb2dfe9-c2e4-4f40-877d-0f22ead3196b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef812128-c67c-4e9e-ba64-5653bd17f77b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa95574a-3863-4465-9265-74d0a268dd6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>548d84aa-c8f2-4019-9714-4dfa835bfffc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e367f4d4-bc9d-491a-9757-c7a6fb7c872b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b3aeb21e-ddc9-400b-8b8e-a692cc5e442c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/Delete,Copy and Move Operations of product in Inventory</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ca5537e-aa3f-4334-ba3a-c3b7cd483828</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fb2dfe9-c2e4-4f40-877d-0f22ead3196b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4fecaa8-45f6-4a3b-8a5a-09235f1ec124</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef812128-c67c-4e9e-ba64-5653bd17f77b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa95574a-3863-4465-9265-74d0a268dd6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>548d84aa-c8f2-4019-9714-4dfa835bfffc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7b3c050-18b7-46f6-9f1b-ea62e54be902</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fab8d24-41d4-40b2-8b6f-a8bbb041916f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>81e13027-11ba-440b-823e-1d6ae82e45f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/Inventory(Verify add,copy,move between location)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05fdf10e-5729-4522-9bef-d312c0e52544</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d22159de-afdd-42c4-92fa-1d6666bd66bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13409e4c-4ad0-4884-8e06-5fa3024c61ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d92a973d-514c-47fd-9fb2-ab068795fb0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff9ae9f0-3861-4ce1-926a-3a9c176e0ae7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd1d3c9d-6d18-4b7d-a7ca-6f06a433a00a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44406214-0f3f-4c66-8477-c1099ba4d123</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fb27b74-f511-4665-8b24-31ee3106b7ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c5834b6-e117-4004-9e1c-55b1c211fcaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ba55b95-33e2-455d-886b-717f66e3e9e6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
