<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>iosRegressionScanInventoryTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>190af352-c0a4-4880-b673-45aee3cdc2d7</testSuiteGuid>
   <testCaseLink>
      <guid>e5607532-95a0-4277-bad5-67c549d5ae2d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/Scan Test Cases/TC_R_019_verifyThatUserIsAbleToIncreaseTheProductQuantityByScanningTheSameBarcodeAgain</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfb5463c-ef99-418d-9232-a78c0ede4559</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ef878c6-fe1a-405b-8803-3ca6140ef97c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ed379c4-bce8-47ed-a5eb-d0dd06738689</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07cac8fd-15c1-441d-8fb9-7c5cfdc42506</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6ef6693-cb94-4342-ae1e-fd7949c59556</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bccf848a-709c-4351-966f-6028f4dc841e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/Scan Test Cases/TC_R_007_verifyThatTheUserIsAbleToUploadTheLocationFromLocationDetailsPage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8232e0b3-cfea-4b9e-a4e5-181289aaca40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0efaa64-5dcb-4229-9e31-e047521771b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3adde9a9-bb08-4ef9-a105-37f7359679dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e58e617-6a8b-4547-afb5-3b5b8ac6fa60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c851f6ff-9a3a-41b6-8d69-6457333668cd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>000e5f35-2f31-4cfa-bd7a-c212aeb31f76</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/Scan Test Cases/TC_R_034_VerifyThatTheUserIsAbleToDoDeleteCopyAndMoveActionsOnDifferentProductsInTheInventoryLocations</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6273bd0f-b06f-4147-9338-9162c8eebd14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e059c2a-0798-464d-b2fb-ad3f0358a43e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05493609-51ec-498d-bcc5-a3806bd25cdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c177d248-46a9-4803-bc6d-faf3f0af219e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ddd4b1c-a6ec-4df5-b307-4f546326f4b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4049340-0431-4a16-85bc-38113f795dc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e96b020c-248b-4b82-84ed-500f2796d703</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e17d21c0-f7e5-4c1e-83b7-a9b3205b9213</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>038b8211-2365-49a7-b682-c846dfc22f4a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d70961b3-357e-4a96-a623-61ba0f761e6a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/Scan Test Cases/TC_R_018_verifyThatWhenUserTapsOnRemoveButtonInTheInventoryScanResultPageOfAnAlreadyScannedProductItGetsRemoved</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5950ac15-d96c-47e3-8602-dce32832c5c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15311d93-b186-4539-88c9-013955ac3e44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c45cfafc-4406-43ce-9e5a-c3efa5d38e6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5a8ab81-6128-4d80-8888-0120a0510518</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ae1a2d9-6a78-4fe8-9686-ab747ec1ae77</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f921bb1-8bdd-43ba-bc9b-e11e2c98670a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/Scan Test Cases/TC_R_020_verifyThatTheUserIsAbleToShareTheProductDetailsFromTheLocationDetailsPage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26dfb16d-d2df-405f-8712-d4f3ec06be73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d6563bd-3acc-40b9-9ee0-72e12b0ffa5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f168128-c823-4dcb-8027-1cc4044e3f04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08b2fb12-1ffe-4caa-a740-2a2a304e5b85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cf47ad5-31e8-49d7-b6a9-ba5c6d1095ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efe23545-a070-4aa4-89b0-877888da0549</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc23efde-345d-4076-bc43-9771d10d1489</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>82b243f9-0e03-44c3-bd9f-793cf394fd19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/Scan Test Cases/TC_R_046_verifyThatTheUserIsAbleToDoCopyAndMoveActionsOnSameProductsInTheInventoryLocations</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7c6a101-9902-4d14-8b8c-eb26e9dbf964</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d08197b-ce7f-4bb0-b04f-daa25052c73c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcd39d5e-8323-448a-9830-ec615544bbcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e1c2d3b-14d1-4118-8353-6af6fe0d5f71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de2d1173-6fef-4ac1-a6d9-97f61bcecb58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c88f0a1b-6190-4969-a6ee-6fb9a13ae9bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfca21d6-1a22-4af2-b312-6bbc26d84192</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53ed444f-c3e8-44a5-83b1-72dae0f8e219</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b01905a6-6f52-47dd-8a9f-3949467160fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/Scan Test Cases/TC_R_003_verifyDetailsSuchAsLocationCountInventoryValueUpdatesAfterLocationDeletion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce83d0f6-b64d-43cc-895c-80196da8aeda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c59ccf31-587f-41a9-9175-93cbf4fbbec2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84f98b23-4002-4e66-b71e-94345f408d3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0210c2ac-bb12-441b-9aba-03a07f499035</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ee2221e-9395-4244-bf44-a49eadcb1b81</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c8acd4fb-feaf-4b5c-a5d6-23c22de559df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/Scan Test Cases/TC_R_021_verifyThatTheUserIsAbleToDeleteTheProductFromLocationDetailsPage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8aa528db-05f5-4f7b-8fff-ef43808b2c16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e9d6bd9-8bd6-49b2-b9df-84271064d3d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a18f0013-9808-4409-be7a-1d2e23a4f1ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21f809b4-0e9d-4cab-97f7-8af69e5c4400</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8007995b-d754-4ab1-a965-83eb21ece9a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee05636e-eef7-448d-a800-510bbb666fc0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d05472b8-bde1-4ab4-8495-721da9a9a130</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/Scan Test Cases/TC_R_010_verifyThatInTheLocationDetailsPageTheAddedProductsAreListedInReverseChronologicalOrder </testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9e7d10d-8935-4f2c-a14b-1973198ac60f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57694bab-13f2-4a21-86a6-97dda5b6be07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d34ed936-a8d6-4538-8f00-23d49f403c44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f86c51f-c891-4ef6-bdba-58728db93683</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cb53523-20f6-44f3-9424-5df7538ceb17</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d75ed26-1058-4f1b-821d-cddb8bb2e859</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca1bc8f7-899d-4f00-b41f-d7f74c9c8fbf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>67fbe05c-3dcc-4412-a22f-3969d5064149</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/Scan Test Cases/TC_R_023_verifyThatTheUserIsAbleToUploadTheLocationFromLocationDetailsPage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5b49d63-cfed-419a-be87-31b8531271ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96d4c384-0e25-4d04-9c06-b9d9921bf0ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29b89f10-c107-4e20-9b46-73b812637a07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2ce5182-c72c-4e2f-9576-7060108c6233</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>769553a0-9e20-41e9-a715-d5f5dcbb609f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d959a575-c015-4e59-b39d-8a1b606452ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/Scan Test Cases/TC_R_015_verifyThatTheUserIsAbleToDeleteInventoryAndLocation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>726a234c-cc29-46e6-a51c-5d6e909ea63b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a92c899-747a-46dd-9b54-5b50412b912e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e3f23b6-1078-461f-abc4-5b0325f87637</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35d19441-05a0-4487-a92c-df13bc8a7b8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d852407-f3e8-4a2b-82ad-d86ac825ee18</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>35aa01d1-9be6-4768-913c-7b1139db32ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/Scan Test Cases/TC_R_024_verifyThatTheUserIsAbleToCopyTheTextFromSearchBox</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e446dc6-a564-41bb-b0a1-10417506ba57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19c9714a-d396-41c1-81c2-a3dd9be9d065</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8270d1a6-5528-4150-96a4-bcde46a078b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/Scan Test Cases/TC_R_017_verifyThatContinueBrowsingButtonInInventoryScanConfirmationPopUpWorkingFineWhileDoingScanFromTheLocationLandingPage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31e502c9-17b9-4d5f-ba9a-1fdaf1484688</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>945e2480-1246-44fd-b51b-b63ccdb76c84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c59de9d-92a3-4d79-8a1b-f846bcf5bc33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ec202d2-9b8a-4460-a135-eed21dfd395f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4991f361-b03a-4ce6-a57a-455809a32b89</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
