<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>iosSmoke</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>76d79b93-2a60-4640-8fc4-cea8784389b3</testSuiteGuid>
   <testCaseLink>
      <guid>781d70f0-39c0-49cf-8a30-bf348737c45c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Carts/TC_OE_014_verifyThatTheUserIsAbleToSubmitTheOrderAfterEditingTheOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c3f082c-3b61-4282-a800-e3f9a38b6c38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9405a11-43f0-4c92-8c30-c2d52250f30b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50c406d3-af6f-4292-a9c3-9b1f1e594d24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d94f1677-ea04-4546-ae36-de2c47122cd1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e76bbe20-b9e0-4dee-8c73-c46d6c9a2520</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b0891e33-a1cc-49ee-9f40-860545645eaa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Carts/TC_OE_010_verifyThatTheUserIsAbleToCreateAnOrderBySearchFromDashboardAndCartsScreen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca0b90f7-1e41-4b2b-8a54-4844bc3990aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75a0f99d-b6dc-49ce-8f8b-d8394e99d52b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4fa8ec4-c23d-42fc-b880-504d4a83a742</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14481009-fea4-4d96-83b9-5456125716cc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>07ae33e7-d38f-405c-a8fa-97c58c4f4a0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Carts/TC_OE_013-verifyThatTheUsersAbleToPlaceAllOrdersnAdUploadAllOrders</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1cc4607-36e0-4162-bde6-71675ffe6810</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a524225-be7a-4997-888c-01306d7e783e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>453f05a4-04ca-4466-b2c9-cd54b0a4433b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50990783-d8a6-4107-928e-ec7101563306</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74cb2936-4d88-489b-9474-45807acc5a50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fafa22fc-840d-45cf-8b80-80b003626db8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>665f2d57-275a-4773-b66c-aaf051cd3d14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46b11b28-933f-4588-91ed-c9798a5a8347</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7ad66fc9-0ff8-4b62-ba19-8c31f0b5b341</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Carts/TC_OE_012_verifyThatTheUserIsAbleToUploadAndPlaceOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca0b90f7-1e41-4b2b-8a54-4844bc3990aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75a0f99d-b6dc-49ce-8f8b-d8394e99d52b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4fa8ec4-c23d-42fc-b880-504d4a83a742</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14481009-fea4-4d96-83b9-5456125716cc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4cdca96-6671-48c7-9c1d-2ebd30d21b42</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Carts/TC_OE_015_verifyThatTheUserIsAbleToDeleteTheOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c3f082c-3b61-4282-a800-e3f9a38b6c38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1169aee0-4f50-483c-b9d4-250bdd80b8e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9405a11-43f0-4c92-8c30-c2d52250f30b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50c406d3-af6f-4292-a9c3-9b1f1e594d24</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e55d489c-4189-4075-be2f-a5c990189b3a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Account Selection/TC_OE_002_verifyThatTheUserIsAbleToPerformAnAccountSelectionUsingTheAccountOptionAvailableFromDashboadCartAndInventoryPages</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb0d0e60-c03b-4615-8443-734ef797afe3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a47a4c56-67c2-4cda-bd67-5c333a349e65</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>476207fd-8b17-47aa-aea9-6fea22eede62</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/TC_OE_003_verifyThatTheUserIsAbleToCreateInventoryLocationAddProductsCopyMoveProductsToLocation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7c6a101-9902-4d14-8b8c-eb26e9dbf964</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d08197b-ce7f-4bb0-b04f-daa25052c73c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcd39d5e-8323-448a-9830-ec615544bbcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de2d1173-6fef-4ac1-a6d9-97f61bcecb58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>574701a1-2ba8-4be8-acbc-edcec06f1043</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82f036cd-beb9-4317-91e2-005beced9fc8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53ed444f-c3e8-44a5-83b1-72dae0f8e219</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db58be5a-09c1-4409-8d72-0441ae832555</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ac704a7-806d-45b1-9503-d29675e78c1c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/TC_OE_008_verifyThatTheUserIsAbleToDeleteInventoryAndInventoryLocation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fa615c2-c825-46d8-a357-16dffbf2a7c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ff4fc47-f855-4124-be66-3969bea28b49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d50ec92d-931f-4d65-9c06-904aca2b41e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fb90834-590c-4af5-b424-77b459f1d992</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e43ddbcd-8859-4899-be45-8e75dbd54e92</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>466c660a-36b4-47ba-a01d-2012ea26f7bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/TC_OE_009_verifyThatTheUserIsAbleToDoDeleteCopyAndMoveOperationsOfTheProductInTheInventory</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7c6a101-9902-4d14-8b8c-eb26e9dbf964</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d08197b-ce7f-4bb0-b04f-daa25052c73c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcd39d5e-8323-448a-9830-ec615544bbcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de2d1173-6fef-4ac1-a6d9-97f61bcecb58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>574701a1-2ba8-4be8-acbc-edcec06f1043</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8be6b4c-4a93-41ce-9bee-6462def6902a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82f036cd-beb9-4317-91e2-005beced9fc8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53ed444f-c3e8-44a5-83b1-72dae0f8e219</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db58be5a-09c1-4409-8d72-0441ae832555</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a236b255-77f4-4f52-8dca-1d6b137521c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/TC_OE_004_verifyThatTheUserIsAbleToEditAndUpdateInventoryAndInventoryLocationName</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7c6a101-9902-4d14-8b8c-eb26e9dbf964</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d08197b-ce7f-4bb0-b04f-daa25052c73c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcd39d5e-8323-448a-9830-ec615544bbcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de2d1173-6fef-4ac1-a6d9-97f61bcecb58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>574701a1-2ba8-4be8-acbc-edcec06f1043</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>653626df-4e41-43af-bbb0-14591815637c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/TC_OE_007_verifyThatTheUserIsAbleToUploadAndShareProductDetailsInTheInventory</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fa615c2-c825-46d8-a357-16dffbf2a7c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ff4fc47-f855-4124-be66-3969bea28b49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d50ec92d-931f-4d65-9c06-904aca2b41e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fb90834-590c-4af5-b424-77b459f1d992</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e43ddbcd-8859-4899-be45-8e75dbd54e92</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9072858-b0cb-435f-865d-74268070ee1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Inventory/TC_OE_005_verifyThatTheUserIsAbleToAddProductInTheInventoryBySearch</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ce0325e-2a45-499b-8ac4-8de7dd7d9b94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a7dd058-d3f0-46f2-a72e-0dd148c4829c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dce0347d-009a-45d5-87fa-c95b6f675ca6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8137d2d5-8b70-4f75-828b-1c06dbc37cb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb51c68a-4dcd-4ba4-8886-558f89601510</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7dc221e-aaef-40a8-b6ee-41e521cd6810</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/LogIn/TC_OE_001_verifyThatTheUserShouldBeAbleToLoginInOrderExpressAppUsingValidLoginCredentials</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>429797af-a19a-4737-9a3c-7160b578f614</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Receiving/TC_OE_023_verifyThatTheUserIsAbleToEditTheCountValueOfTheProductsInTheTote</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f803a15-1a3a-4bbb-aac8-2baeef241e99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbd78dc1-73ce-42e1-9242-9cdc9a8f895c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae58e2fe-5be7-4b0d-94fa-a44f510777de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Receiving/TC_OE_021_verifyThatTheUserIsAbleToSelectReceiveToteButtonAndUploadSelectedTotes</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84537d08-a0ee-4be0-a0f4-67da9a38435d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a56e9be-70f9-4738-bb67-9d86a81bf816</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f080220-0d59-442e-aabd-d94d33884a76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3811c501-31c0-440f-91b3-31072af0c4a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0be87968-3d30-4716-bec9-65e28fbd8b89</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Receiving/TC_OE_020_verifyThatTheUserIsAbleToSwapBetweenShipmentsAndInvoices</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab1311fd-8a38-410d-8083-bf4a28e00892</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52ed210b-2227-4369-9eb7-c8df140896f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed35deca-12f1-4c66-96b4-865134c60bb7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Receiving/TC_OE_038_verifyThatTheUserIsAbleToGetTheScanResultByDoingTheToteLevelScanning</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e739b874-e879-49f9-8645-fbffdb9f6d2d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>39bbc2f4-299b-4c38-893b-5f637a372b1e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Receiving/TC_OE_018_verifyThatTheUserIsAbleToViewReceivingPageAndReceivingData</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab1311fd-8a38-410d-8083-bf4a28e00892</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52ed210b-2227-4369-9eb7-c8df140896f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0babb231-908b-4633-a307-2e47c8b8474c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Receiving/TC_OE_022_verifyThatTheUserIsAbleToDoAllowOveragesAndEditCountOfProduct</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>896867d4-bdd3-48a4-b3c1-0543463d1370</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5161bef-a512-4ca1-9de4-fa34381adba7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f6c47f3f-a1bf-4e3f-98cd-e0abd474750e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Receiving/TC_OE_026_verifyThatTheUserIsAbleToSubmitTheIssue</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f3094bf-d90f-4e81-a65e-394944675d1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86a979a2-3ad5-49c4-9e8e-d7871972c8df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af72f5c2-8521-4029-a73e-91fd8bfdb21b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c09cbb4c-8e56-4a66-b7ef-5e805276c652</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f6a91ea-3724-43e0-9f87-a5f5dc42fccd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c024cf7-7703-4c80-a518-9dec0221a18d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92a5d36d-87c4-4300-8827-5d6ca5f6fb63</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>06ca8b0a-6b4e-4058-9294-46bc0038d2d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Receiving/TC_OE_025_verifyThatTheUserIsAbleToSearchTheProductsByScanningTheBarcodeWhichAreAlreadyReceived</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>525b8abf-461b-451e-a43c-266b5a743a21</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e7299df-be95-469b-b458-630867d82447</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Receiving/TC_OE_024_verifyThatTheUserIsAbleToSearchTheProductsAndTotesManuallyWhichAreAlreadyReceived</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4b158c1-1518-4f3a-80cf-1f65d04521d6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>762d5130-ef58-4573-acb3-620a94a1ab7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Receiving/TC_OE_019_verifyThatTheUserIsAbleToViewTheReceivingDataOfThePreviousDay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab1311fd-8a38-410d-8083-bf4a28e00892</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52ed210b-2227-4369-9eb7-c8df140896f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9ab36b4b-87c8-4ed9-8add-9ee671ea31cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/Audits/TC_OE_027_VerifyThatTheUserIsAbleToViewTheAuditsPageAndChangeDifferentCIMaccountUsingAccountSelctionIcon</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52080859-3884-4aeb-9f07-f5edb481baf6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>836c2e97-31c8-4f09-b34d-7f9d732be9c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b4ffa55-6844-4c74-9028-e0380fa1bb86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd058327-640a-4ce0-9af6-4a09c63730fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75f204a2-3abd-46c1-ac8a-60de9da3bc0e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
