<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Token Generator API</name>
   <tag></tag>
   <elementGuidId>9a85926d-964b-4940-bc9e-cafcaa91679b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sm-session</name>
      <type>Main</type>
      <value>${smsession}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-api-key</name>
      <type>Main</type>
      <value>${x-api-key}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>WCToken</name>
      <type>Main</type>
      <value>${WCToken}</value>
   </httpHeaderProperties>
   <katalonVersion>8.1.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>${token-generator-api-host}/${env}/api/v1/token-generator/application/mobile/generate?user=${user}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.token-generator-api-host</defaultValue>
      <description></description>
      <id>da73aeb9-f74d-4f67-945b-aced4b15589c</id>
      <masked>false</masked>
      <name>token-generator-api-host</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.env</defaultValue>
      <description></description>
      <id>7ff21113-52d6-45b1-be10-686b7a809d62</id>
      <masked>false</masked>
      <name>env</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.user</defaultValue>
      <description></description>
      <id>e2e2e8e8-967a-4221-ba87-fbae7defddd1</id>
      <masked>false</masked>
      <name>user</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.smsession</defaultValue>
      <description></description>
      <id>78c7fc5f-752b-4d83-a0f9-1e827e946200</id>
      <masked>false</masked>
      <name>smsession</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.x-api-key</defaultValue>
      <description></description>
      <id>8536a223-8f77-436f-bb93-8f465ad7cb0c</id>
      <masked>false</masked>
      <name>x-api-key</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.WCToken</defaultValue>
      <description></description>
      <id>c191f64e-716c-44ea-ae27-c14465640e8e</id>
      <masked>false</masked>
      <name>WCToken</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
